Ogrevalna naloga

Napiši program, ki se začne z opisom ovire v eni vrstici, na primer

In [89]:
import numpy as np

zemljevid = [
    "......",
    "..##..",
    ".##.#.",
    "...###",
    "###.##",
]
zemljevid = np.array(zemljevid)
print(zemljevid)

['......' '..##..' '.##.#.' '...###' '###.##']


Resevanje z numpy.

In [90]:
zemljevid = np.array([[0] + [int(c == "#")
                      for c in vrstica] + [0] for vrstica in zemljevid])
print(zemljevid)
lokacije = np.nonzero(zemljevid)

print(lokacije)


[[0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 1 1 0 1 0 0]
 [0 0 0 0 1 1 1 0]
 [0 1 1 1 0 1 1 0]]
(array([1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64), array([3, 4, 2, 3, 5, 4, 5, 6, 1, 2, 3, 5, 6], dtype=int64))
